### PR TITLE
Bump to version 5.3.179

### PR DESCRIPTION
**Pull request by AlexandreSi**

### CODE REVIEW

**Comment by AlexandreSi** [comment]
@barthalion @hfiguiere I'm pinging you since you seem to be the only persons that contributed to this repo outside of GDevelop team.

There seem to be an issue regarding the CI, the check does not go to green although everything seems fine with the builds:
https://buildbot.flathub.org/#/builders/6/builds/78076
https://buildbot.flathub.org/#/builders/5/builds/9645

Would you happen to know what's wrong?

**Comment by hfiguiere** [comment]
it's called **patience**

Sometime things take longer than we want and impatience is the enemy of it all.

I have strictly no power here either.

**Comment by AlexandreSi** [comment]
Sorry for that then, I was used to seeing the CI complete quickly. I'll come back later then.

**Comment by hfiguiere** [comment]
see 
image

**Comment by AlexandreSi** [comment]
Sorry it's just that it used to be way quicker before and since I have not worked on it since a long time, I was not aware the CI was taking longer now.
Now I'm aware and sorry again for the ping.

**Pull request merged**
