### PR TITLE
Add arm64 support

### PR DESCRIPTION
**Pull request by wjt**

### CODE REVIEW

**Comment by wjt** [comment]
For context, we at Endless OS want to preinstall GDevelop, and we release arm64 builds of the OS.

I don't actually have an arm64 device! I will ask my colleagues who do to test this, but I suggest that there is no real cost to adding an arm64 build since the `.deb` is right there.

**Comment by 4ian** [comment]
Thanks for doing this! Ping me if you need something :)

**Comment by wjt** [comment]
Yes, please merge this and #31 :)

**Comment by ClementPasteau** [comment]
Didn't see it either! I've rebased and will merge both PRs. thanks @wjt !!

**Pull request merged**
